global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - alerts.prometheus.yml

scrape_configs:
   - job_name: 'prizeprice-api'
     metrics_path: /metrics
     scheme: http
     bearer_token: ${METRICS_TOKEN}
     static_configs:
       - targets: ['172.20.0.4:3001']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
